### ISSUE TITLE
Translation PL

### ISSUE THREAD

**Issue by YoMan12** [sander1988/Indego#246]
I think there's missing "Sleeping" in "mower_state_detail" in pl.json file.

**Comment by sander1988** [comment]
Thank you for reporting. Same issue for the other languages. I will fix this.

**Comment by YoMan12** [comment]
@sander1988 I see that nobody wants to translate it :( I can do it but I'm not familiar with github at all and I do not know how to do this in a proper way. 
If You can show me the proper path I can do that or I can paste a file right here.

**Comment by WhyLev** [comment]
🤖 **AI Summary of the solution:**

The 'Sleeping' state was added to the 'mower_state_detail' in the pl.json file after reporting the issue.
