### ISSUE TITLE
Documentation does not specify how to re-authenticate to SingleKey

### ISSUE THREAD

**Issue by mashdk** [sander1988/Indego#247]
## The problem

There doesn't seem to be a description in readme.md on how to re-authenticate / get new token from SingleKey ID.

## Expected behavior

Some way to re-authenticate from inside HA without removing the integration with all entities and their IDs.

## Steps to reproduce

Difficult, I guess,
This happened after the connection to the Bosch cloud was lost for a day.
Indego Connect app couldn't connect either.
Today it could connect from Indego Connect app, but it required re-authentication with SingleKey ID.
The HA integration couldn't load, even after re-initializing, because the token was expired/invalid.

## Environment

Indego integration version 5.7.0

HA OS 12.4 on HA Yellow
Core: 2024.7.3
Supervisor: 2024.08.0

## Logs

2024-08-11 11:52:17.946 ERROR (MainThread) [homeassistant.helpers.config_entry_oauth2_flow] Token request for indego failed (invalid_grant): AADB2C90080: The provided grant has expired. Please re-authenticate and try again. Current time: 1723369937, Grant issued time: 1723180920, Grant sliding window expiration time: 1723200273.

## Additional information

Integration cannot be re-initialized.

**Comment by sander1988** [comment]
A few months ago I have looked into this. Unfortunately I couldn't find a callback in HomeAssistant to retrigger the oauth2 flow. So the only way to resolve this atm is by removing and re-adding the integration.

I have opened a [discussion](https://github.com/home-assistant/architecture/discussions/1126) on the HA boards. Feel free to upvote if you think this is also useful for you.

**Comment by WhyLev** [comment]
🤖 **AI Summary of the solution:**

The integration cannot be re-initialized due to the lack of a callback in Home Assistant to retrigger the oauth2 flow; users must remove and re-add the integration.
